### ISSUE TITLE
Install Info

### ISSUE THREAD

**Issue by baurbr** [andreadegiovine/homeassistant-energy-cost#1]
Hi Andrea,
I am trying to install integration but I am asked for a sensor “Entità Fascia PUN (F1, F2, F3)”.
What kind of sensor should it be? 
In configuration I have turned off the "Tariffa+PUN" slider.
thank you in advance for your response

**Comment by andreadegiovine** [comment]
Hi @baurbr 
in Italy we have 2 modes of rate “Mono rate” (all time/day same kwh price) and “Flex rates” (kwh price based on time/day rules).

If you select on first step “Flex rates” you need to install this integration [Prezzi PUN del mese](https://github.com/virtualdj/pun_sensor) ad use the sensor that return the current rate (F1,F2,F3)

**Comment by baurbr** [comment]
Hi, I have an ibrid rate. Different fixed price for F1, F2 and F3. 
Is this rate available in the integration ? 
Thanks

**Comment by andreadegiovine** [comment]
Yes but this integration need to get the current rule to apply using one sensor from this integration [Prezzi PUN del mese](https://github.com/virtualdj/pun_sensor) or any other sensor that return your current rule to apply (F1, F2, F3).

Use “Flex rates” on first step and select the sensor from [Prezzi PUN del mese](https://github.com/virtualdj/pun_sensor) or other sensor that expose the current rule.
