### ISSUE TITLE
Inserimento dati

### ISSUE THREAD

**Issue by ChristianG75** [andreadegiovine/homeassistant-energy-cost#2]
Ciao,
nelle impostazioni 
- nell' entità consumo iniziale devo selezionare il "Contatore Channel 1 energy " del mio shelly che mi monitora l'energia?
- nei costi fissi posso inserire il costo mensile del canone RAI ?
- è possibile utilizzare i dati dei tre sensori PUN con il prezzo ricavati da https://github.com/virtualdj/pun_sensor ?

Grazie mille 
Christian

**Comment by andreadegiovine** [comment]
Ciao @ChristianG75 

1. l’entità consumo da scegliere deve essere espressa in kWh mensili.
2. Nei costi fissi metti pure canone rai (mensile) ed eventuale costo commercializzazione (mensile).
3. Se la tua tariffa è +PUN ed hai l’integrazione attiva, scegli pure l’entità che espone la fascia corrente (F1,F2,F3) e nei campi dedicati agli importi delle fasce metti solo il sovrapprezzo applicato dal gestore.

**Comment by ChristianG75** [comment]
Ciao, potresti spiegarmi come passare da kWh a kWh mensili ? ( oppure se riesci ad integrarlo )
Grazie Christian

**Comment by andreadegiovine** [comment]
@ChristianG75 qui trovi giusto un esempio che fa al caso tuo https://www.home-assistant.io/integrations/utility_meter/

`
# Example configuration.yaml entry
utility_meter:
  energy:
    source: sensor.energy_in_kwh
    cycle: monthly 
`

**Comment by ninoger** [comment]
Ciao, grazie e complimenti per il lavoro. Volevo chiedere 0,01328 cos'è? Si deve modificare/personalizzare?
Grazie

**Comment by andreadegiovine** [comment]
Ciao @ninoger e grazie.
Quella è la tariffa al kwh o il sovrapprezzo per kwh rispetto al PUN se hai una tariffa basata sul PUN.

Nello specifico quello è il mio sovrapprezzo rispetto al PUN

**Comment by ninoger** [comment]
Ciao, grazie per la risposta.
Io ho una tariffa fissa monoraria di 0,132. Come dovrei regolarmi? Perdonami, ma non ho ben compreso come fare a inserire i giusti dati. Grazie

**Comment by andreadegiovine** [comment]
Nel primo step scegli monoraria e togli la selezione del PUN, nel secondo step inserisci quella cifra nell’unico campo tariffa che trovi.
Non dimenticare di aggiungere canone e commercializzazione nei costi fissi.

**Comment by ninoger** [comment]
> Nel primo step scegli monoraria e togli la selezione del PUN, nel secondo step inserisci quella cifra nell’unico campo tariffa che trovi.
> Non dimenticare di aggiungere canone e commercializzazione nei costi fissi.

Perfetto. Provo e ti faccio sapere. Rinnovo i miei complimenti. È molto utile.

**Comment by ninoger** [comment]
Tutto perfetto e dati attendibili. Grazie.
Buona giornata e buon lavoro.
